/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rectanglesexample.Presentation.View;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JTextField;
import rectanglesexample.Presentation.Controller.*;

/**
 *
 * @author Usuario
 */
public class Canvas extends javax.swing.JFrame implements ICanvas {

    CCanvas controller;
    /**
     * Creates new form Canvas
     */
    public Canvas() {
        initComponents();
        controller = new CCanvas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lblWidth = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        btnPaint = new javax.swing.JButton();
        btn183 = new javax.swing.JButton();
        btn122 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 190, 190));
        getContentPane().add(txtWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 40, -1));
        getContentPane().add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, -1));

        lblWidth.setText("Width:");
        getContentPane().add(lblWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblHeight.setText("Height:");
        getContentPane().add(lblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btnPaint.setText("add");
        btnPaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        btn183.setText("183x244");
        btn183.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn183ActionPerformed(evt);
            }
        });
        getContentPane().add(btn183, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, -1));

        btn122.setText("122x244");
        btn122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn122ActionPerformed(evt);
            }
        });
        getContentPane().add(btn122, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaintActionPerformed
        // TODO add your handling code here:
        controller.paint();
    }//GEN-LAST:event_btnPaintActionPerformed

    private void btn122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn122ActionPerformed
        // TODO add your handling code here:
        controller.paintDefault(1);
    }//GEN-LAST:event_btn122ActionPerformed

    private void btn183ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn183ActionPerformed
        // TODO add your handling code here:
        controller.paintDefault(2);
    }//GEN-LAST:event_btn183ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn122;
    private javax.swing.JButton btn183;
    private javax.swing.JButton btnPaint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTextField width() {
        return this.txtWidth;
    }

    @Override
    public JTextField height() {
        return this.txtHeight;
    }

    @Override
    public void close() {
        this.dispose();
    }

    @Override
    public Graphics graphics() {
        return this.getGraphics();
    }
}
